// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS4oPG7gtwXRsH-eZ9YKzirBx5HbCxuRg',
    appId: '1:712713831993:web:eb0189127a3af260a92fe8',
    messagingSenderId: '712713831993',
    projectId: 'drop-taxi-a0feb',
    authDomain: 'drop-taxi-a0feb.firebaseapp.com',
    storageBucket: 'drop-taxi-a0feb.firebasestorage.app',
    measurementId: 'G-5D3HSGKWE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJnMOJhG2LwESnD5eaIakhGEnFXQ6rK7g',
    appId: '1:676938262003:android:cf9a1c8a771211382ade86',
    messagingSenderId: '676938262003',
    projectId: 'demone-ef35a',
    storageBucket: 'demone-ef35a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCjuhJwtcCIPysTiEc99y84jMfXHz59eI',
    appId: '1:676938262003:ios:def6db6287abe2d82ade86',
    messagingSenderId: '676938262003',
    projectId: 'demone-ef35a',
    storageBucket: 'demone-ef35a.firebasestorage.app',
    iosBundleId: 'com.example.droptaxi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC05j5AyHzXzYT6VwqFIlA44togW_Hx08E',
    appId: '1:712713831993:ios:60969fc7d9dbcfcca92fe8',
    messagingSenderId: '712713831993',
    projectId: 'drop-taxi-a0feb',
    storageBucket: 'drop-taxi-a0feb.firebasestorage.app',
    iosBundleId: 'com.example.droptaxi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS4oPG7gtwXRsH-eZ9YKzirBx5HbCxuRg',
    appId: '1:712713831993:web:6ce3a2941eedb80fa92fe8',
    messagingSenderId: '712713831993',
    projectId: 'drop-taxi-a0feb',
    authDomain: 'drop-taxi-a0feb.firebaseapp.com',
    storageBucket: 'drop-taxi-a0feb.firebasestorage.app',
    measurementId: 'G-2VKBBF8SWN',
  );

}