// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9fpOvNMDVxWEY5wm5sjXA6csxydQJ74k',
    appId: '1:676938262003:web:288e1c71003cb1a92ade86',
    messagingSenderId: '676938262003',
    projectId: 'demone-ef35a',
    authDomain: 'demone-ef35a.firebaseapp.com',
    storageBucket: 'demone-ef35a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJnMOJhG2LwESnD5eaIakhGEnFXQ6rK7g',
    appId: '1:676938262003:android:cf9a1c8a771211382ade86',
    messagingSenderId: '676938262003',
    projectId: 'demone-ef35a',
    storageBucket: 'demone-ef35a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCjuhJwtcCIPysTiEc99y84jMfXHz59eI',
    appId: '1:676938262003:ios:def6db6287abe2d82ade86',
    messagingSenderId: '676938262003',
    projectId: 'demone-ef35a',
    storageBucket: 'demone-ef35a.firebasestorage.app',
    iosBundleId: 'com.example.droptaxi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCjuhJwtcCIPysTiEc99y84jMfXHz59eI',
    appId: '1:676938262003:ios:def6db6287abe2d82ade86',
    messagingSenderId: '676938262003',
    projectId: 'demone-ef35a',
    storageBucket: 'demone-ef35a.firebasestorage.app',
    iosBundleId: 'com.example.droptaxi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh3FVx3Z1nVmZnM_DliF69X8jnT9F5yPA',
    appId: '1:676938262003:web:8b0319ecd3a10b352ade86',
    messagingSenderId: '676938262003',
    projectId: 'demone-ef35a',
    authDomain: 'demone-ef35a.firebaseapp.com',
    storageBucket: 'demone-ef35a.firebasestorage.app',
  );
}
